apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestra-service-deployment
  labels:
    app: orchestra-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestra-service
  template:
    metadata:
      labels:
        app: orchestra-service
    spec:
      containers:
      - name: orchestra-service
        image: 092356264921.dkr.ecr.eu-central-1.amazonaws.com/orchestra-service:77a13ece8d73f7e65ee0cb85481e543fceb78371
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5