apiVersion: v1
kind: Service
metadata:
  name: orchestra-service-service
spec:
  selector:
    app: orchestra-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP